services:
  - docker

script:
  - make lint
  - make bundle-prod copy-files

deploy:
  provider: pages
  skip_cleanuo: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
  local_dir: ./dist
