services:
  - docker

script:
  - docker-compose run deno deno lint src
  - docker-compose run deno deno bundle src/index.js dist/bundle.js
  - cp src/index.html dist/index.html

deploy:
  provider: pages
  skip_cleanuo: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
  local_dir: ./dist
